# -*- coding: utf-8 -*-
"""Projeto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hYZis1tn7d7poLZwYINKHZJbTT-imzS7
"""

# features (caracteristicas)(1 sim, 0 não)
# pelo longo? 
# perna curta?
# faz auau?
porco1 = [0, 1, 0]
porco2 = [0, 1, 1]
porco3 = [1, 1, 0]

dog1 = [0,1,1]
dog2 = [1,0,1]
dog3 = [1,1,1]

# 1 => porco, 0 => cachorro
dados = [porco1, porco2, porco3, dog1, dog2, dog3]
classes = [1,1,1,0,0,0]

from sklearn.svm import LinearSVC as LSCV

model = LSCV()
model.fit(dados,classes)

new_animal=[1,1,1]
model.predict([new_animal])

misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

testes = [misterio1, misterio2, misterio3]
previsoes = model.predict(testes)

teste_classes=[0,1,1]

corretos = (previsoes==teste_classes).sum()
total = len(testes)
tx_acertos = corretos/total
porcent=tx_acertos*100
print("taxa de acerto: {:.2f} %".format(porcent))

corretos